### ISSUE TITLE
Localization for MaterialDatePicker

### ISSUE THREAD

**Issue by emptyeye** [GwtMaterialDesign/gwt-material#331] opened 2016-05-25 04:26 UTC
Hello again, when we started using MaterialDatePicker we faced with problem, that we can't translate labels on it's UI. Is it a bug or a feature ? =)

**Comment by kevzlou7979** [comment] 2016-05-25 05:36
Its a feature. You can do PR and study this
http://amsul.ca/pickadate.js/date/.

**Comment by kevzlou7979** [comment] 2016-05-25 08:53
Duplicate of this https://github.com/GwtMaterialDesign/gwt-material/issues/320

**Closed by kevzlou7979** 2016-05-25 08:53 UTC
