### ISSUE TITLE
Card with FAB not working correctly

### ISSUE THREAD

**Issue by PaulKC** [GwtMaterialDesign/gwt-material#491] opened 2016-11-04 10:37 UTC
The FAB on the card does not always reappear after clicking the pause button in the showcase.

http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#cards

Using Chrome 54

**Comment by kevzlou7979** [comment] 2016-11-07 04:33
The issue is related to delay on animation, will take a deep investigation about it.

**Comment by kevzlou7979** [comment] 2016-11-22 02:26
I investigate it thoroughly and came up with the same issue, The Animation is not resetting the classnames which causes inconsitency when we animate the same target widget like the code below.

```java
            new MaterialAnimation().transition(Transition.BOUNCE).animate(row);
            new MaterialAnimation().transition(Transition.JELLO).animate(row);
```

![issue](https://cloud.githubusercontent.com/assets/3138071/20508646/e2a7473e-b09d-11e6-9c78-08e7d8424fa5.gif)

**Comment by kevzlou7979** [comment] 2016-11-22 04:20
Ok got everything sorted, It seems that this code is not well suited for callback.
```javascript
$('#yourElement').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', doSomething)
```
The solution would be use Timer to for durationMillis.
```java
        new Timer() {
            @Override
            public void run() {
                if (callback != null) {
                    callback.call();
                }
                $(element).removeClass(oldClass);
            }
        }.schedule(durationMillis);
```

**Comment by kevzlou7979** [comment] 2016-11-22 05:07
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/4195b3abb99626dc09222dbd9a39e422c32b5664

**Closed by kevzlou7979** 2016-11-22 05:07 UTC
