### ISSUE TITLE
Lean-overlay z-index is decreasing after every page switch

### ISSUE THREAD

**Issue by moschkom** [GwtMaterialDesign/gwt-material#620] opened 2017-04-26 12:30 UTC
The z-index value of the lean-overlay is decreasing when using the application. At some point the NavBar is in front of the lean-overlay.

How to reproduce: 
1. Go to http://gwtmaterialdesign.github.io/gwt-material-demo/#dialogs
2. Open a MaterialModal dialog and memorize the z-index value of the lean-overlay div which is added with the MaterialModal (in my case 1002)
3. Close the dialog and navigate to some other page (e.g. Components > Badges)
4. Go again to the dialogs (Components > Dialogs)
5. Open a MaterialModal and have a look at the z-index value (in my case 994)
6. At this point the Navbar (z-index 998) is already visible/usable

As long as you stay on the same page and open/close a modal the z-index of the lean-overlay is stable. Once you navigate to some other page/url and open/close a modal the z-index is a smaller one.

This issue could be related to #257

**Comment by kevzlou7979** [comment] 2017-04-26 13:30
Thanks for this, as of now we have our Own ModalManager to recalculate the index, I will try to manage to follow all your guides to reproduce it.

**Comment by moschkom** [comment] 2017-04-26 15:25
The ModalManager and the calculated z-index of the MaterialModal looks fine to me. The problem is with the lean-overlay which should grey out everything behind the MaterialModal.

**Comment by gkresic** [comment] 2017-04-29 18:54
Looks like ModalManager prevents using layered modal dialogs (display modal from within modal) that materializecss currently supports (almost) well (at least version bundled with GMD 2.0-rc4).

"Almost", because stacking of modal dialogs works as long as all dialogs in hierarchy are opened/closed in the same order (open A, B, C then close C, B, A). Even basic deviations from this sequence, even as trivial as "open new modal from within onClose() handler of current modal" do break things at some point. But this limitation is bearable, at least more then not being able to use stacked modals at all (for example to ask for confirmation on "delete" action triggered from some modal).

Fixing this modal layering completely would require some small modifications to GMD (for start, see #624), but also better stack calculations in materializecss, which does not handle out-of-order closing of modal dialogs (_stack variable used in openModal/closeModal tracks only total number of modal dialogs and not one with highest lStack counter). I could provide patch for GMD, but I'm not fluent in JS enough to provide working code over there. I do have a proposal for an algorithm and could assist in making a patch, if neccessary.

**Comment by kevzlou7979** [comment] 2017-05-01 00:40
@gkresic Yeah we are happy to receive contributions via Pull Request, then we can review how it will be. For the JS one I think you can start JSINterop to easily update the _stack_variable I hope it;s a global one. We will for your patch.

**Comment by kevzlou7979** [comment] 2017-05-01 01:19
@moschkom Yeah I agree, I just checked the modal index it works well, the only issue that we got is the ```lean overlay``` - the grey panel, probably the good thing or workaround for that is we just need to recalculate it base on modals index, then we can subtract it from 1. 

For example:
If we have a:
Modal - zindex = 1002
Expected Lean Overlay - zindex = 1001

**Comment by kevzlou7979** [comment] 2017-05-01 03:10
Fixed and Added JUnit Test via https://github.com/GwtMaterialDesign/gwt-material/commit/44bc87a2f3b881a1eb507a7ad84a7193f4d31c9d

**Comment by kevzlou7979** [comment] 2017-05-01 03:12
Added Multiple instance demo showcase https://github.com/GwtMaterialDesign/gwt-material-demo/commit/d221981ab4ce62638996d1625613d5dce9eaac6d

**Closed** 2017-05-01 06:29 UTC
Labels: add documentation, add unit test, ready

**Comment by moschkom** [comment] 2017-05-02 08:27
Thank you for the fast fix. I could not reproduce the issue anymore.
