### ISSUE TITLE
MaterialTooltip is shown for hidden element

### ISSUE THREAD

**Issue by magway77** [GwtMaterialDesign/gwt-material#304] opened 2016-04-25 08:33 UTC
Hello guys, thank you for your work.
there are some trouble with MaterialTooltip:
if ui.xml is defined like this:
```xml
<m:MaterialColumn>
    <m:MaterialTooltip text="bla bla bla">
                <wp:PaymentWidget ui:field="paymentWidget" visible="false" .../>
    </m:MaterialTooltip>
</m:MaterialColumn>
```
then in code:
```java
paymentWidget.setVisible(false);
```
then  tooltip is still appear for invisible field.
probably need to add check of visibility
good luck

**Comment by BenDol** [comment] 2016-05-23 04:14
Thanks for the report! Please remember to use code tags in the markdown:
\`\`\`xml
..code..
\`\`\`
Updated for you. Working on resolving this issue.

**Comment by BenDol** [comment] 2016-05-23 05:29
I'm not able to reproduce this, even using the code above, it could be a CSS difference in the PaymentWidget causing issues. if you can show me how to reproduce this using Material widgets I'll review it.

**Comment by magway77** [comment] 2016-05-24 05:29
may be problem is^paiment widget contains Frame
`<ui:UiBinder xmlns:ui='urn:ui:com.google.gwt.uibinder'
             xmlns:g='urn:import:com.google.gwt.user.client.ui'
             xmlns:m="urn:import:gwt.material.design.client.ui">

    <ui:style>

        .buttonPayFrame {
            border: 0px none !important;
            width: 136px;
            height: 31px;
            vertical-align: middle;
        }

    </ui:style>

        <g:Frame styleName="{style.buttonPayFrame}"/>

</ui:UiBinder>`
`public class PaymentWidget
        extends Composite
        implements IsWidget {

    interface PaymentWidgetUiBinder extends UiBinder<Frame, PaymentWidget> {
    }
    private static PaymentWidgetUiBinder uiBinder = GWT.create(PaymentWidgetUiBinder.class);

    private final Frame buttonPay;

    @Inject
    public PaymentWidget() {
        buttonPay = uiBinder.createAndBindUi(this);
        initWidget(buttonPay);
    }

    public String getButtonPayUrl() {
        return buttonPay.getUrl();
    }

    public void setButtonPayUrl(String url) {
        buttonPay.setUrl(url);
    }
}
`
where is url something like this:
`https://money.yandex.ru/embed/shop.xml?account=410011399503669&quickpay=shop&payment-type-choice=on&mobile-payment-type-choice=on&writer=seller&targets=paymeDest&targets-hint=&default-sum=1&button-text=01&successURL=http%3A%2F%2Flocalhost%3A8080%2Fredirecturl`

**Comment by BenDol** [comment] 2016-05-24 06:14
I tried many ways to reproduce this issue without success using this code. Can you create a sample project where the issue can be reproduced? Otherwise I cannot resolve right now. Thanks!

**Comment by kevzlou7979** [comment] 2016-05-24 06:30
Me too im not able to reproduce it

**Closed** 2016-10-20 13:52 UTC
Labels: unconfirmed
