### ISSUE TITLE
MaterialListValueBox is not displaying label

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material#722] opened 2017-10-26 15:02 UTC
I upgraded to 2.1-SNAPSHOT and the labels from MaterialListValueBox dissapeared. It seems like there is no input-field div wrapper anymore.

**Comment by kevzlou7979** [comment] 2017-10-27 09:02
Upon testing the issue both unit test and manual demo testing, we can't reproduce this issue.
Please be concise on giving some code snippets , your test environment (GWT or Errai) , a sample project should be enough to have. 

![screenshot from 2017-10-27 17-00-44](https://user-images.githubusercontent.com/3138071/32096246-74635302-bb38-11e7-812b-a6a9f48d3427.png)

**Comment by kevzlou7979** [comment] 2017-10-27 09:09
Are you using the new feature from 2.1-SNAPSHOT -> MaterialListBox#allowBlank?

**Comment by pfacmf** [comment] 2017-10-27 11:19
I am not sure about the proper way to do this... This is an exported eclipse project. In the screenshot you can see there is no element with the css class I set on listbox. Before the screenshot I ran the list.setVisible(false). 

[gmdtest.zip](https://github.com/GwtMaterialDesign/gwt-material/files/1421839/gmdtest.zip)

![listboxes](https://user-images.githubusercontent.com/4210304/32101384-a71a467e-bb20-11e7-9c47-aabc03c4ac50.png)

**Comment by kevzlou7979** [comment] 2017-10-27 11:26
Thanks @pfacmf  I appreciate this I will try to figure out the issue on this specific usecase.

**Comment by mbudnick** [comment] 2017-10-30 10:12
I have the same problem with 2.0-RC7.
The reason in short: calling reload() before the item is renderd destroyed the input-field div wrapper.

The reason in long:
I use Activities and Places with views as singletons. So I create the view and by filling options programmaticaly reload() will be called.
If this happens before the view is renderd, the input-field div wrapper is deleted.
If setting options without reload() (thanks new feature in RC7), it is all fine.
But my view is a singleton: when the view is reused (options will then not set anymore) reload() is called and destroyed with every call more html.

My workaround is to @Override reload() to do nothing and call reload only when the item is visible.

Unfortunately it is difficult to create a simple small code example.

**Comment by kevzlou7979** [comment] 2017-10-30 11:09
Thanks @mbudnick for the feedback, Just finished the 2.1 Service Worker enhancements, Now im back on 2.0 debugging.

**Comment by kevzlou7979** [comment] 2017-10-30 23:49
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/cac27b55aef92c546c903e6c2a410d7a8afd226b

**Closed** 2017-10-30 23:49 UTC
Labels: ready
