### ISSUE TITLE
DatePicker year dropdown

### ISSUE THREAD

**Issue by simerlec** [GwtMaterialDesign/gwt-material#529] opened 2016-12-12 10:01 UTC
Hey,

first of all thanks for all the work you guys are doing - great stuff, keep it up.

Is there a way to increase the year range on a datepicker (selectionType="YEAR_MONTH_DAY") with the year dropdown? Currently I am only able to choose ±5 years, which is kinda horrid when selecting a birth date.

Thanks and kind regards

Chris

**Comment by kevzlou7979** [comment] 2016-12-12 10:12
Hi there,

Yeah probably this is a very useful feature with it comes to birth date.

+1

**Comment by kevzlou7979** [comment] 2016-12-12 10:19
Here I found a very useful information. It seems that if we put ```selectYears: 100``` it will display a lists of 100 year selection.

https://github.com/amsul/pickadate.js/issues/193

**Comment by simerlec** [comment] 2016-12-12 10:29
Thanks. I'll try it out and let you know :)

**Comment by kevzlou7979** [comment] 2016-12-12 10:34
The ```selectYears: 20``` is not yet available on MaterialDatePicker 2.0-SNAPSHOT. Will test it out if it works. Then submit a commit.

**Comment by kevzlou7979** [comment] 2016-12-12 12:50
Ok I have implemented the feature on 2.0-SNAPSHOT. 
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/99f2ceb973db9b810fbdc7ceb7e6e990f97bc56a

![datepicker](https://cloud.githubusercontent.com/assets/3138071/21100023/9972b462-c0ac-11e6-9ee0-03794c9d67ae.gif)

**Comment by simerlec** [comment] 2016-12-12 12:53
Awesome, great job!!

One thing I noticed by looking at your demo above is that the selected date (yellow circle) gets deselected on year change. Is this behaviour intended?

kind regards

**Comment by kevzlou7979** [comment] 2016-12-12 12:54
Yeah it was intended to be like that.

**Comment by simerlec** [comment] 2016-12-12 12:55
Roger that.

Thank you very much for the fast fix!

**Closed** 2016-12-21 12:26 UTC
Labels: feature request, ready
