### ISSUE TITLE
Position of placeholder labels when in sidenav

### ISSUE THREAD

**Issue by leforthomas** [GwtMaterialDesign/gwt-material#457] opened 2016-09-19 15:59 UTC
If I put some TextBox, or basically any form element, in a sidenav, the placeholders locations get reset and they end up overlaid on the text. See image attached.

It is very simple to reproduce, you only need to add a few form elements to the sidenav in the demo MenuView.xml file. File in a couple of values and at some point the placeholders positions are reset and cover the actual text input.

![gwtmaterial](https://cloud.githubusercontent.com/assets/1318091/18639091/d7430546-7e92-11e6-8f14-a320b963a3b6.png)

**Comment by kevzlou7979** [comment] 2016-09-21 00:56
Yeah , I will rework how sidenav handle its children, I think it causes by the ListItem which has a predefined style. I go to a conclusion that all MaterialLinks should only added to ListItem not the other widgets.

**Comment by BenDol** [comment] 2016-09-21 01:10
This is because certain CSS rules conflict with other widgets inside the side nav. We have concluded that we won't be providing fixes for other widgets inside the `MaterialSideNav` as its not its intended functionality. However these can be fixed within your own application by overriding certain CSS rules to function they way you are needing. If you would like to provide any CSS overrides to fix issues with other widgets inside the `MaterialSideNav` we are open to pull requests.

**Closed by BenDol** 2016-09-21 01:10 UTC
Labels: wontfix

**Comment by leforthomas** [comment] 2016-09-21 07:34
OK, I would like to provide a fix if I can understand the issue. Can you explain what the css rule conflict is about in this case? say with a MaterialTextBox for instance.

**Comment by leforthomas** [comment] 2016-09-21 08:03
I don't think it's a pure CSS issue BTW. I just looked at what goes on wrt CSS and the "active" class is removed spuriously, causing the label to fall on the text. I set a few breakpoints to understand what was triggering the issue but no luck. I imagine there is something else running in the back, eg some jquery code?

**Comment by leforthomas** [comment] 2016-09-21 10:05
This seems to be the culprit, in MaterialSideNav, wrap method

```
        // Collapsible and Side Porfile should not be selectable
        final Widget finalChild = child;
        if(!isNotSelectable) {
            // Active click handler
            finalChild.addDomHandler(new ClickHandler() {
                @Override
                public void onClick(ClickEvent event) {
                    clearActive();
                    finalChild.addStyleName("active");
                }
            }, ClickEvent.getType());
        }

```

What is this for? Any work around given my user case?

**Comment by BenDol** [comment] 2016-09-22 02:08
The active style is for marking a collapsible as the active item. This is of course a CSS class, so if you were to override the `active` class rule you can resolve this. Or you can override it for specific components it is affecting.

However why is the removal of `active` class causing your label to fall on to the text? Has to be something to do with the styling applied.

**Comment by BenDol** [comment] 2016-09-22 02:14
Unfortunately I'm not able to reproduce the issue you are having. Can you provide the content of your `MaterialCollapsibleBody` from the uibinder so I can see how you have set it up?

**Comment by leforthomas** [comment] 2016-09-28 10:55
Yes, well, in the end, I just overrode the wrap method and got rid of the code mentioned above. It seems to have solved my issue without causing any other noticeable problems.

To reproduce the problem, you just need to add some form elements in the sidenav. Easiest is to use the demo code. Just add a couple of textboxes in the MenuView.xml file. Type in some text and click in and out (focus/unfocus) the textboxes. At some point the label collapses and overlays the text in the textbox.
