### ISSUE TITLE
Split Panel fill when close to the edge

### ISSUE THREAD

**Issue by 0x3333** [GwtMaterialDesign/gwt-material#507] opened 2016-11-16 09:54 UTC
In the first [Split Panel example](http://gwtmaterialdesign.github.io/gwt-material-demo/#splitpanel)
when the handle is close to the edge it fill in:

![screen shot 2016-11-16 at 07 52 24](https://cloud.githubusercontent.com/assets/289289/20342490/bd5c8df2-abd1-11e6-982e-3ecade98c0fd.png)

Both ends:

![screen shot 2016-11-16 at 07 54 16](https://cloud.githubusercontent.com/assets/289289/20342520/e6d2203e-abd1-11e6-8e78-ef0995c8ec92.png)

**Comment by kevzlou7979** [comment] 2016-11-16 13:41
Thanks for catching this will look this out

**Comment by kevzlou7979** [comment] 2016-11-17 03:45
I figured out that this was caused by padding inside the demo showcase

**Comment by kevzlou7979** [comment] 2016-11-17 04:16
Fixed via https://github.com/GwtMaterialDesign/gwt-material-demo/commit/763be45a9d459b8839fa2d57fbff1215f4d78f77

**Closed by kevzlou7979** 2016-11-17 04:16 UTC
