### ISSUE TITLE
gwt-material and gwt-material-table not compatible

### ISSUE THREAD

**Issue by adibacco** [GwtMaterialDesign/gwt-material#622] opened 2017-04-27 07:29 UTC
In my project I'm using gwt-material 2.0-SNAPSHOT and gwt-material table 1.0-SNAPSHOT and I get this error when compiling:

[INFO] --- gwt-maven-plugin:2.8.0:compile (gwt-compile) @ ylct ---
[INFO] Compiling module gwt.material.design.ylct.GwtMaterialDesignYLCT
[INFO]    Tracing compile failure path for type 'gwt.material.design.client.ui.table.TableSubHeader'
[INFO]       [ERROR] Errors in 'jar:file:/home/ubuntu/ypacket2/mavenrepo/com/github/gwtmaterialdesign/gwt-material-table/1.0-SNAPSHOT/gwt-material-table-1.0-SNAPSHOT.jar!/gwt/material/design/client/ui/table/TableSubHeader.java'
[INFO]          [ERROR] Line 61: Cannot reduce the visibility of the inherited method from MaterialWidget
[INFO]    [ERROR] Aborting compile due to errors in some input files
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
﻿
It seems a problem in get-material-table jar not in my code.

**Comment by kevzlou7979** [comment] 2017-04-27 07:36
Duplicate of https://github.com/GwtMaterialDesign/gwt-material/issues/621

**Closed by kevzlou7979** 2017-04-27 07:36 UTC

**Comment by kevzlou7979** [comment] 2017-04-27 09:53
Also as for the information, https://github.com/GwtMaterialDesign/gwt-material/pull/587. We updated the versions for DataTable and JQUERy to be uniform on all GMD Projects.

Current SNAPSHOT - 2.0-SNAPSHOT
Next Release - 2.0-rc5
