### ISSUE TITLE
MaterialCollection: border between items sometimes doesn't show on Firefox

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#193] opened 2015-12-09 01:18 UTC
This is weird. Here is a screenshot from the demo app on Chrome:

![screenshot from 2015-12-08 23 11 36](https://cloud.githubusercontent.com/assets/7464735/11673608/690cfda6-9e01-11e5-8957-1d611a153a88.png)

And this is a screenshot on Firefox:

![screenshot from 2015-12-08 23 11 16](https://cloud.githubusercontent.com/assets/7464735/11673618/7908d964-9e01-11e5-8831-40eac71d146f.png)

Note that on Firefox, some borders between items aren't showed. Zooming at the page makes some borders to show and some to disappear (the screenshot was taken at 100% zoom).

The border behaviour was always consistent on Chrome in my tests.

**Comment by kevzlou7979** [comment] 2015-12-09 04:08
I tried Firefox 42.0 and the border is ok.

**Comment by gilberto-torrezan** [comment] 2015-12-09 04:16
Same version here. Did you try to change the the zoom of the page to see if it affects the borders?

Maybe the platform is affecting the rendering somehow? I'm always on Linux.

**Comment by kevzlou7979** [comment] 2015-12-09 04:26
yes i tried to zoom in / out and its working. I think its a linnux firefox problem.

**Comment by kevzlou7979** [comment] 2016-11-09 14:06
With the BrowserStack help, I can now reproduce the issue in Mozilla 42 with success. I investigate deeply the root cause of the issue on borders and figure it out after spending some time browsing on the forums. And the main issue is the class ``` waves-effect ``` which has a css attribute ``` will-change ``` and the only solution is to set it ``` initial ``` for a workaround.

See the screenshot below. Will commit a fix sooner.
![borderless](https://cloud.githubusercontent.com/assets/3138071/20140882/9b2efdea-a6c8-11e6-985b-de3a2552bede.gif)

**Comment by kevzlou7979** [comment] 2016-11-09 14:11
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/7ff1e8a383b520a47463c95658c33fc364a352ba

**Closed by kevzlou7979** 2016-11-09 14:11 UTC
Labels: bug, help wanted

**Comment by BenDol** [comment] 2016-11-09 14:31
:+1:
