### ISSUE TITLE
MaterialCutOut not working on Safari & iOS browsers

### ISSUE THREAD

**Issue by wkok** [GwtMaterialDesign/gwt-material#227] opened 2016-01-05 15:30 UTC
@gilberto-torrezan MaterialCutOut is a very nice component, thank you.

In desktop Safari as well as iOS browser the component does not seem to work correctly. it is easier to illustrate with screenshots so here goes:

PS: The same behaviour can be seen on the showcase demo: http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#cutouts

This shows how it works correctly in Chrome:
<img width="762" alt="screen shot 2016-01-05 at 5 05 50 pm" src="https://cloud.githubusercontent.com/assets/5214136/12118624/323f79ea-b3d0-11e5-8afe-1fc0fe2f5cb5.png">

But under Safari desktop it looks like the overlaying blue background is missing:
<img width="755" alt="screen shot 2016-01-05 at 5 06 06 pm" src="https://cloud.githubusercontent.com/assets/5214136/12118642/52108aca-b3d0-11e5-8ca0-de1d88324e27.png">

Same can be seen on iOS:
![img_2232](https://cloud.githubusercontent.com/assets/5214136/12118850/5bc89d86-b3d1-11e5-9879-a1759bdbf9f8.jpg)

**Comment by gilberto-torrezan** [comment] 2016-01-05 15:45
Too bad I don't have an Apple device to test on. Off the top of my head I imagine three situations:

Safari doesn't understand box-shadow (I don't think this is true), or
The function that gets the right box-shadow color is not working on Safari, or
The way the animation keyframes are created is not supported on Safari.

I need assistance from an Apple boy/girl to fix that =)

**Comment by kevzlou7979** [comment] 2016-01-06 03:04
@gilberto-torrezan I think you can install into your Ubuntu : Wine application then install Safari / Opera browser, or you can try this http://techhamlet.com/2012/03/how-to-easily-install-safari-in-linux-the-new-updated-guide/

**Comment by gilberto-torrezan** [comment] 2016-01-06 12:54
@kevzlou7979 The problem of installing Safari on Linux is that the base version of that package is the Windows version of Safari, which is pretty outdated (5.1.7) and not supported anymore by Apple.

Opera on the other hand have a native, updated version for Linux, but the bug was filled specifically for Safari, so not testing on Safari is not advisable.

(By the way, the example from the demo app is working ok on Opera).

That being said, I'll try some fixes in blind mode, but to close this issue I really need assistance from somebody with an Apple device - mainly to test on iOS.

**Comment by wkok** [comment] 2016-01-06 13:19
@gilberto-torrezan I am happy to assist in testing on Safari & iOS
Unfortunately I'm not a css expert, but I can surely try out your suggested css changes on these platforms

**Comment by gilberto-torrezan** [comment] 2016-01-06 13:50
Ok I improved the way the CutOut handles css animations, and created a PR. If the background color is not yet set when opening the CutOut, the animation can be disabled at all, by calling `setAnimated(false)`. @wkok Can you test with my branch, and if still doesn't work, test by setting the animation to `false`? If everything fails we have a serious problem =(

**Comment by wkok** [comment] 2016-01-08 14:32
@gilberto-torrezan Sorry about the delay in testing this, I'm getting to it now just not entirely sure which branch to test this with now?

I see it was merged into master, although MaterialCutOut was originally only in release_1.5?
I've noticed that you've also deleted your branch called fix227 which I assume I needed to test with.

**Comment by gilberto-torrezan** [comment] 2016-01-08 16:53
@wkok It is now merged to [gwt-material-addins](https://github.com/GwtMaterialDesign/gwt-material-addins) project - you don't need to use my fork.

**Comment by wkok** [comment] 2016-01-09 09:15
@gilberto-torrezan I've tested with setAnimated(true) and setAnimated(false) but the effect is still exactly the same unfortunately.

**Comment by gilberto-torrezan** [comment] 2016-01-09 16:30
@wkok Ok, I have one more guess: [the support for rem units](http://caniuse.com/#search=rem). To test it, open the Cut Out and in the browser inspector change the `box-shadow` declaration to use any other unit instead of `rem`.

![screenshot from 2016-01-09 14 26 03](https://cloud.githubusercontent.com/assets/7464735/12217111/225d5afa-b6dd-11e5-8456-6e1d859d6227.png)

The screenshot shows the declaration when using animation. Without the animation, the `box-shadow` declaration is not in a keyframe, but directly in the element css.

**Comment by gilberto-torrezan** [comment] 2016-01-09 16:52
Ok, nevermind - I tested with Safari 5.1 on a Windows VM and it doesn't seem to be the real problem. box-shadow, rem units, css animation keyframes, all work on the browser, but it still doesn't open the Cut Out.  I'll debug here and create a new PR when I find something.

**Comment by gilberto-torrezan** [comment] 2016-01-09 17:15
@wkok I just tested with `setAnimated(false)`, and the Cut Out is working ok on Windows Safari 5.1. Can you post a code where the bug occurs so I can test with it?

**Comment by gilberto-torrezan** [comment] 2016-01-09 18:01
New PR, this time I removed completely the keyframes definition and replaced it with a simple and more portable CSS transition.

On my tests with Safari 5.1 on Windows, the animation doesn't run, but the background is set correctly without problems. Before this patch, the background was set only when using `setAnimated(false)`.

**Comment by wkok** [comment] 2016-01-09 22:14
@gilberto-torrezan I tested with your latest changes in PR12 but the problem persists.

Some good news though, I seem to have narrowed it down to the method MaterialCutOut.setCircle(true);

When I remove the setCircle() method, the cutOut works properly in both Safari & iOS, only with a square  highlight instead of the circle obviously. As soon as I add back setCircle(true), then the problem returns

**Comment by gilberto-torrezan** [comment] 2016-01-10 15:55
@wkok Thanks for narrowing it down, but on Windows Safari the Cut Out opens with or without `setCircle(true)`. But nevertheless, I'll set `-webkit-border-radius` together with `border-radius` on the CSS to see if it fixes the problem.

**Comment by gilberto-torrezan** [comment] 2016-01-18 14:06
@wkok Any news?

**Comment by wkok** [comment] 2016-01-18 18:20
@gilberto-torrezan I've updated  & tested now, but still the same result unfortunately.

**Comment by gilberto-torrezan** [comment] 2016-01-18 20:10
@wkok Well, at this point I can't help anymore without the actual device. My suggestion is to play with the options of the component, and its CSS, to see if any combination results in successful rendering of the Cut Out.

Since the problem seems to be related to `setCircle(true)` (which internally sets the `border-radius` of the focus component to 50%), try setting it to false and putting a `border-radius` directly on the component, like this:

```css
.material-cutout-focus {
    border-radius: 32px; /* assuming the target component have 64px of size */
}
```
Another test that can be done is to create any other component with `setCircle(true)` (like a MaterialIcon) and set a `border-shadow` to it, to see if the browser behaves correctly.

```java
MaterialIcon icon = new MaterialIcon(IconType.ADD);
icon.setCircle(true);
icon.getElement().getStyle().setProperty("boxShadow", "0px 0px 0px 100rem rgba(0, 0, 255, 0.5)");
```

**Comment by BenDol** [comment] 2016-05-23 05:36
I have tested this on the latest version of Safari without any problems, seems to be a css style issue causing the problems in Safari, until someone is able to provide sample code to reproduce it I am closing this issue.

**Closed by BenDol** 2016-05-23 05:36 UTC
