### ISSUE TITLE
Sidenav activates

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material#586] opened 2017-03-20 10:52 UTC
In 2.0-rc3 all work fine, in 2.0-rc4 don't work

> Exception caught: Cannot find an activator for the MaterialSideNav, please ensure you have a MaterialNavBar with an activator setup to match this widgets id.
> Syh_g$ @ ConsoleLogger.java:32
> p3g_g$ @ SimpleConsoleLogHandler.java:36
> D2g_g$ @ Logger.java:312
> C2g_g$ @ Logger.java:302
> $2g_g$ @ Logger.java:236
> $pd_g$ @ LogConfiguration.java:169
> Cpb_g$ @ Impl.java:186
> ppb_g$ @ Impl.java:293
> (anonymous) @ Impl.java:77
> ConsoleLogger.java:55 Exception: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: Cannot find an activator for the MaterialSideNav, please ensure you have a MaterialNavBar with an activator setup to match this widgets id.
> ConsoleLogger.java:32 Error: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: Cannot find an activator for the MaterialSideNav, please ensure you have a MaterialNavBar with an activator setup to match this widgets id.
>     at Q$c_g$.xgb_g$ [as createError_0_g$] (Throwable.java:121)
>     at Q$c_g$.Hgb_g$ [as initializeBackingError_0_g$] (Throwable.java:113)
>     at Q$c_g$.rgb_g$ (Throwable.java:74)
>     at Q$c_g$.Xgb_g$ (Exception.java:33)
>     at Q$c_g$.dhb_g$ (RuntimeException.java:33)
>     at Q$c_g$ (UmbrellaException.java:65)
>     at VZc_g$.a$c_g$ [as doFire_0_g$] (SimpleEventBus.java:203)
>     at VZc_g$.h$c_g$ [as fireEventFromSource_0_g$] (SimpleEventBus.java:96)
>     at lr_g$.R_g$ [as fireEvent_2_g$] (PresenterWidget.java:264)
>     at lr_g$.Q_g$ [as fireEvent_1_g$] (PresenterWidget.java:250)
>     at Xz_g$ (LoginEvent.java:23)
>     at Cr_g$.Er_g$ [as onSuccess_1_g$] (LoginPresenter.java:113)
>     at Cr_g$.Fr_g$ [as onSuccess_2_g$] (LoginPresenter.java:107)
>     at iFh_g$.PCh_g$ [as onResponseReceived_0_g$] (AbstractRequestCallback.java:94)
>     at jN_g$.lN_g$ [as onResponseReceived_0_g$] (AdminConsoleDispatcher.java:69)
>     at G_c_g$.J_c_g$ [as fireOnResponseReceived_0_g$] (Request.java:250)
>     at Q0c_g$.R0c_g$ [as onReadyStateChange_0_g$] (RequestBuilder.java:412)
>     at XMLHttpRequest.<anonymous> (XMLHttpRequest.java:329)
>     at mpb_g$ (Impl.java:239)
>     at ppb_g$ (Impl.java:291)
>     at XMLHttpRequest.<anonymous> (Impl.java:77)
> Syh_g$ @ ConsoleLogger.java:32
> Uyh_g$ @ ConsoleLogger.java:41
> Tyh_g$ @ ConsoleLogger.java:36
> p3g_g$ @ SimpleConsoleLogHandler.java:38
> D2g_g$ @ Logger.java:312
> C2g_g$ @ Logger.java:302
> $2g_g$ @ Logger.java:236
> $pd_g$ @ LogConfiguration.java:169
> Cpb_g$ @ Impl.java:186
> ppb_g$ @ Impl.java:293
> (anonymous) @ Impl.java:77
> ConsoleLogger.java:55 Caused by: java.lang.RuntimeException: Cannot find an activator for the MaterialSideNav, please ensure you have a MaterialNavBar with an activator setup to match this widgets id.

in 2.0-rc4 does not exists data-activates

![nav](https://cloud.githubusercontent.com/assets/439337/24096840/579a4324-0d74-11e7-836f-2a94abe8107a.png)

**Comment by kevzlou7979** [comment] 2017-03-21 04:20
Can you confirm on 2.0-SNAPSHOT if the issue is gone? Also take note that it's a follow up issue on https://github.com/GwtMaterialDesign/gwt-material/issues/569

Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/a9d6e94bf0ab02a3adec45b907823ca564a55ec4

**Comment by LeshaRB** [comment] 2017-03-21 07:52
Yes I can confirm!

2.0-SNAPSHOT  also don't work

**Comment by kevzlou7979** [comment] 2017-03-21 08:08
Still throwing the error. Are you sure  you have added your sidenav?

**Comment by LeshaRB** [comment] 2017-03-21 08:27
Yes I sure

I change in pom.xml 2.0rc-3 to 2.0-rc4 and it dont' work

**Comment by kevzlou7979** [comment] 2017-03-21 09:44
Have you changed your pom.xml GMD Version to 2.0-SNAPSHOT?

**Comment by kevzlou7979** [comment] 2017-03-21 09:45
```xml
       <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material</artifactId>
            <version>${gwt-material.version}</version>
        </dependency>
```

**Comment by esocode** [comment] 2017-03-22 17:57
I experienced the same problem with rc4 and snapshot (I didn't try rc3). It seems that there is something like a "race condition" during initialization. MNB.onLoad() only adds the side nav activation button if it finds the _data-activates_ attribute. But the ActivatesMixin is declared as `ActivatesMixin<>(navMenu);`, so the attribute will only be there if the navMenu exists (which it doesn't because it is only added if the attribute exists...). I fixed that by overriding `setActivates(...)` and inserting the navMenu before invoking super.

**Comment by kevzlou7979** [comment] 2017-03-23 05:05
@esocode Thanks for the follow up, can you open a PR for 

>  I fixed that by overriding setActivates(...) and inserting the navMenu before invoking super.

So that we can review your fixed and patched it to rc5. Thanks again.

**Comment by esocode** [comment] 2017-03-23 09:28
I just subclassed MNB in my own project and overrode the setActivates() method to fix the problem but I don't think that is the optimal solution of this problem because there's still the code in the onLoad() method which should be inspected. Therefore I would suggest that the original developer has a look at the code to check how it can be optimized.

**Comment by esocode** [comment] 2017-03-23 12:09
I just noticed that the problem has been fixed in the latest snapshot by adding the navMenu in the constructor.

**Comment by kevzlou7979** [comment] 2017-03-23 12:18
Ok so it's working now into your side?

**Comment by esocode** [comment] 2017-03-23 12:22
Yes, with the most recent code it work as expected.

**Comment by kevzlou7979** [comment] 2017-03-23 12:23
Ok I will close now this issue, thanks again for the confirmation.

**Closed by kevzlou7979** 2017-03-23 12:23 UTC
Labels: bug, cosmetic, ready
