### ISSUE TITLE
MaterialDatePicker - page jumps to bottom

### ISSUE THREAD

**Issue by simerlec** [GwtMaterialDesign/gwt-material#573] opened 2017-03-01 09:18 UTC
Hello,

for some reason, when you open the MaterialDatePicker modal, the page scrolls to the bottom. Can be reproduced using the Demo Site (http://gwtmaterialdesign.github.io/gwt-material-demo/#pickers) and choosing the date using the first picker.

IIRC this was not always an issue.

kr

Chris

**Comment by reofake** [comment] 2017-03-01 10:23
Duplicate of https://github.com/GwtMaterialDesign/gwt-material/issues/558

**Comment by simerlec** [comment] 2017-03-01 10:30
ah, thanks reo - I've overlooked that.

**Closed** 2017-03-01 10:30 UTC

**Comment by kevzlou7979** [comment] 2017-03-01 10:50
@reofake Thanks to follow up this issue.

**Comment by reofake** [comment] 2017-03-01 12:34
No problem !
